/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC725Y, IERC725YInterface } from "../IERC725Y";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "value",
        type: "bytes",
      },
    ],
    name: "DataChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
    ],
    name: "getData",
    outputs: [
      {
        internalType: "bytes",
        name: "value",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC725Y__factory {
  static readonly abi = _abi;
  static createInterface(): IERC725YInterface {
    return new utils.Interface(_abi) as IERC725YInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC725Y {
    return new Contract(address, _abi, signerOrProvider) as IERC725Y;
  }
}
